In [10]:
import numpy as np
from sklearn.metrics import confusion_matrix

In [2]:
a = [[1, 2], [2, 2]]
b = [[3, 3], [2, 4]]

In [3]:
print(f'a.dot.b = \n{np.dot(a, b)}')
print(f'b.dot.a = \n{np.dot(b, a)}')

a.dot.b = 
[[ 7 11]
 [10 14]]
b.dot.a = 
[[ 9 12]
 [10 12]]


## simple perceptron

In [4]:
input_data = np.random.random([10, 4])
w = np.random.random([2, 4])
b = np.random.random(2)

In [8]:
p = {}
for i in range(2):
    res = []
    for j in range(10):
        res.append(np.dot(input_data[j], w[i]) + b[i])
    p[fr'p{i}'] = res

p

{'p0': [np.float64(2.0971176231746527),
  np.float64(1.6196309246175509),
  np.float64(1.338319958889088),
  np.float64(1.5110845999390636),
  np.float64(1.3862825106963),
  np.float64(1.9066736078409527),
  np.float64(1.7251045177697653),
  np.float64(1.5192360859022411),
  np.float64(1.9617141619092888),
  np.float64(2.2283885769667564)],
 'p1': [np.float64(1.1657923200926166),
  np.float64(0.7128224428754176),
  np.float64(0.6064119632435353),
  np.float64(0.7606404170524326),
  np.float64(0.6668485738576282),
  np.float64(0.9988806929339737),
  np.float64(0.7943353957911679),
  np.float64(0.7682498964055545),
  np.float64(1.0340448237337265),
  np.float64(1.3169786912973214)]}

In [13]:
a = [1, 0, 1, 0, 1, 1, 1, 0, 1, 1]
p = [1, 1, 0, 0, 1, 1, 0, 1, 1, 0]

tp, tn, fp, fn = 4, 1, 2, 3

confusion_matrix(a, p)

array([[1, 2],
       [3, 4]])